// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRqkKcWMNLND1t8p2-96a6lv7C-StEG-A',
    appId: '1:739154453909:web:1d78c0d098debab1fec29c',
    messagingSenderId: '739154453909',
    projectId: 'bookapp-4ecfb',
    authDomain: 'bookapp-4ecfb.firebaseapp.com',
    storageBucket: 'bookapp-4ecfb.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYOGSiAxRsyVq28aQfBSugBjSsAMUpfac',
    appId: '1:739154453909:android:747e71eba77440ccfec29c',
    messagingSenderId: '739154453909',
    projectId: 'bookapp-4ecfb',
    storageBucket: 'bookapp-4ecfb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpquyVsZVgjs89ue4QJrSFqrL0Vknm_hU',
    appId: '1:739154453909:ios:4c4b780071c96f22fec29c',
    messagingSenderId: '739154453909',
    projectId: 'bookapp-4ecfb',
    storageBucket: 'bookapp-4ecfb.appspot.com',
    iosBundleId: 'com.example.bookapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDpquyVsZVgjs89ue4QJrSFqrL0Vknm_hU',
    appId: '1:739154453909:ios:913ca621d2f1f2c7fec29c',
    messagingSenderId: '739154453909',
    projectId: 'bookapp-4ecfb',
    storageBucket: 'bookapp-4ecfb.appspot.com',
    iosBundleId: 'com.example.bookapp.RunnerTests',
  );
}
